server:
  port: 5000


spring:
  freemarker:
    expose-request-attributes: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/telegram
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  telegrambot:
    botUserName: '@travel1ing_bot'
    botToken: 1383524175:AAGWhBL6RMB3XXhPCMCsCC5PAH2pQoKa13A
    webHookPath:  https://eab0e81440d6.ngrok.io

    proxyType: SOCKS5
    proxyHost: localhost
    proxyPort: 9150
