server:
  port: 5000

spring:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/telegram
    username: postgres
    password: Upiver88

  telegrambot:
    botUserName: '@travel1ing_bot'
    botToken: 1383524175:AAGWhBL6RMB3XXhPCMCsCC5PAH2pQoKa13A
    webHookPath:  https://061c5456d453.ngrok.io

    proxyType: SOCKS5
    proxyHost: localhost
    proxyPort: 9150